version: 0.0 #required
os: linux #windows or linux

Files: #optional
 - source: files/newpage.html
   destination: /var/www/html

Permissions: #optional for linux only
 - object: /var/www/html
   pattern: newpage.html
   mode: 755
   type:
    - file
    
Hooks:
 BeforeInstall: 
  - location: scripts/webserver-stop.sh
 AfterInstall:
  - location: scripts/webserver-start.sh